### ISSUE TITLE
License and authorship

### ISSUE THREAD

**Issue by aubertc** [jweeks2023/LQICM-Benchmark#1]
Please, add a license to your work.
Also, there is probably no need to indicate your name in benchmark.c

https://github.com/jweeks2023/LQICM-Benchmark/blob/2a2d7800cbfe8b662cdc71cef294f188de8c3c09/benchmark.c#L108-L110

simply claim authorship in the Readme.md file, and that should do.

Cf. https://softwareengineering.stackexchange.com/a/101770 for more context on why "signing" your code is not a good idea.

**Comment by jweeks2023** [comment]
License added, and thanks for the informative link! We went with a Creative Commons 4.0 License to encourage modification and forking.
