### ISSUE TITLE
Improving readme

### ISSUE THREAD

**Issue by aubertc** [jweeks2023/LQICM-Benchmark#2]
Your Readme.md file has many issues:

- "To Do!" should have been in a different file, or handled through issues. If it is clear, then remove it in any case.
- "THIS IS A WIP!!!": please, avoid all caps, and phrase this disclaimer in a more refined way.
- "(crazy ik)": what does this mean?
- "Code that you want to benchmark": I'm sure the specification is _a bit more precise_ than that. Could you provide a template to help the user in getting started?
- "Save your code.": what are you referring to?
- "In your terminal, naviagte to the LQICM-Benchmark folder. (Use cd)": aren't we there already?
- "Compile your code using clang in the terminal. I recommend using this line: clang-15 benchmark.c -O0 -o benchmark -lm.": Ok, but it compiles just fine with gcc as well. Why would clang be needed / recommended?
- "Inserting Code": again, an example to get started would help. What is the protocole, here? Do I need 2 files, 1 file, particular methods, a `main` method, can I load libraries, etc.

**Comment by jweeks2023** [comment]
The Readme.md had a lot of temporary additions to it while we were working on it a bunch. A part of the final revisions includes revising this so that it's as clear and easy to follow as possible.
