### ISSUE TITLE
Provide sample code to benchmark

### ISSUE THREAD

**Issue by aubertc** [jweeks2023/LQICM-Benchmark#3]
I must admit that I am clueless as to what to do to [insert code](https://github.com/jweeks2023/LQICM-Benchmark/blob/main/README.md#inserting-code). Could you please provide either better instructions, or an example file?

**Comment by jweeks2023** [comment]
Added better instructions to both the CodeToTest folder and the section in question. Also provided some sample code to test the functionality of the benchmark.
