### ISSUE TITLE
Parametrize benchmark.c

### ISSUE THREAD

**Issue by aubertc** [jweeks2023/LQICM-Benchmark#4]
The file [benchmark.c](https://github.com/jweeks2023/LQICM-Benchmark/blob/main/benchmark.c) should be easily portable.
To that end, please, consider making

- The compiler name (and its path),
- The output folder name,
- The input folder name,

parameters. Using `define` directive like for `ITERATIONS` is fine.

**Comment by jweeks2023** [comment]
Thanks for the suggestion, I have parametrized those variables. The only one that I may not have correctly implemented is the first point.

**Comment by jweeks2023** [comment]
Update, added a new parameter `COMPILERPATH` that contains the path to the `COMPILER` parameter.
